DROP TABLE IF EXISTS parts;
CREATE TABLE parts(
id INT(11) NOT NULL AUTO_INCREMENT,
type VARCHAR(20) NOT NULL,
name VARCHAR(255) NOT NULL,
count INT(11) NOT NULL,
PRIMARY KEY (id))
DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_unicode_ci;
